[package]
name = "domaker-transpiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
domaker-parser = { version = "0.1.0", path = "../parser" }
thiserror = "1.0.56"
